language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "nightly" # currently 3.7-dev
  - "pypy"

install: 
  - pip install coveralls

script: 
  - coverage run test_copyingmock.py

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
